Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import string

from wordcloud import STOPWORDS    #nhá»¯ng tá»« khÃ´ng cÃ³ Ã½ nghÄ©a láº¯m nhÆ° the, a, and,...
from tqdm import tqdm              # Ä‘á»ƒ hiá»‡n thanh quÃ¡ trÃ¬nh cho biáº¿t Ä‘Ã£ cháº¡y Ä‘Æ°á»£c Ä‘áº¿n Ä‘Ã¢u
from sklearn.metrics import f1_score, precision_score, recall_score, confusion_matrix, ConfusionMatrixDisplay
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 7[0m
[0;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[0;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mstring[39;00m
[1;32m----> 7[0m [38;5;28;01mfrom[39;00m [38;5;21;01mwordcloud[39;00m [38;5;28;01mimport[39;00m STOPWORDS    [38;5;66;03m#nhá»¯ng tá»« khÃ´ng cÃ³ Ã½ nghÄ©a láº¯m nhÆ° the, a, and,...[39;00m
[0;32m      8[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtqdm[39;00m [38;5;28;01mimport[39;00m tqdm              [38;5;66;03m# Ä‘á»ƒ hiá»‡n thanh quÃ¡ trÃ¬nh cho biáº¿t Ä‘Ã£ cháº¡y Ä‘Æ°á»£c Ä‘áº¿n Ä‘Ã¢u[39;00m
[0;32m      9[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmetrics[39;00m [38;5;28;01mimport[39;00m f1_score, precision_score, recall_score, confusion_matrix, ConfusionMatrixDisplay

[1;31mModuleNotFoundError[0m: No module named 'wordcloud'
ModuleNotFoundError: No module named 'wordcloud'

